version: "{build}"
clone_depth: 1
clone_folder: c:\gopath\src\github.com\rhysd\vimwasm-try-plugin
environment:
    GOPATH: c:\gopath
init:
    - set PATH=C:\msys64\mingw64\bin;%PATH%
install:
    - echo %PATH%
    - echo %GOPATH%
    - go version
    - go env
    - go get -v -t -d ./...
build: off
test_script:
    - go build
    - go test -v -race
deploy: off
